Feature: removing players once keep alive expires
lycan-city/werewolf-functions pull request #1
Opened 2018-11-20 22:17 UTC by wovalle

Closes https://github.com/lycan-city/werewolf-virtual-cards/issues/33

2018-11-20 23:31 UTC, vetom commented on functions/package.json
> +    "firebase-tools": "^6.1.1",
Good one!

2018-11-21 00:18 UTC, vetom requested changes
BTW I liked the single commas, can you add the linter rule?

2018-11-21 00:18 UTC, vetom commented on functions/src/index.ts
> +  console.log('players with keep alive', playersWithKeepAlive);
Remove all console.log calls so we can keep the log clear for errors.

2018-11-21 00:18 UTC, vetom commented on functions/src/index.ts
> +    .collection('keepAlive')
Iterate over all the players online it's an expensive operation, use a `where` to get only the players outside the threshold.

2018-11-21 00:18 UTC, vetom commented on functions/src/index.ts
> +  for (let i = 0; i < playersWithKeepAlive.length; i++) {
This loop won't be necessary after getting the players filtered.

2018-11-21 00:18 UTC, vetom commented on functions/src/index.ts
> +      const updatedParty = {
Remember to check if `gameInProgress === true` so you kill the player in the game.

2018-11-21 00:30 UTC, wovalle commented on functions/src/index.ts
> +      const updatedParty = {
Done

2018-11-21 00:30 UTC, wovalle commented on functions/src/index.ts
> +  for (let i = 0; i < playersWithKeepAlive.length; i++) {
Yes, it will

2018-11-21 18:58 UTC, wovalle commented on functions/src/index.ts
> +    .collection('keepAlive')
With the current data structure is not possible to optimize the query.

2018-11-21 18:58 UTC, wovalle commented on functions/src/index.ts
> +  console.log('players with keep alive', playersWithKeepAlive);
Updated the logging strategy.

2018-11-21 22:58 UTC, vetom commented on functions/src/index.ts
> +  for (let i = 0; i < playersWithKeepAlive.length; i++) {
True!

2018-11-21 22:58 UTC, vetom approved these changes

2018-11-22 22:04 UTC, mamodom commented on functions/src/index.ts
> +    playersActive: playersWithKeepAlive.length - playersRemoved.length,
I think `activePlayers` sounds better

2018-11-24 22:32 UTC, merged