Feat/better project structure
lycan-city/werewolf-functions pull request #2
Opened 2018-11-21 20:16 UTC by wovalle

My intention with this commit is to have a flatter file/folder structure and eliminate the need of two package.json's.

Oh, and hot reloading is now working with `tsc`.

2018-11-21 22:59 UTC, vetom approved these changes

2018-11-22 22:08 UTC, mamodom requested changes

2018-11-22 22:08 UTC, mamodom commented on package.json
> +    "concurrently": "^4.1.0",
This should be a devDependency

2018-11-24 14:32 UTC, wovalle commented
@mamodom done

2018-11-24 22:23 UTC, mamodom approved these changes

2018-11-24 22:34 UTC, merged